[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# rustflags = [
#  "-C", "link-arg=-Tlink.x",
#   "-C", "link-arg=-Tdefmt.x",
# ]
runner = 'probe-rs run --chip nRF52833_xxAA' # <- change for your chip


[udeps]
target = "thumbv7em-none-eabihf"

[build]
target = "thumbv7em-none-eabihf"

[embed]
target = "thumbv7em-none-eabihf"
